# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Rémy Gardette
email: contact@remyg.fr
description: Java/JEE Technical Team Leader
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://remyg.fr" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: remygardette
github_username:  RemyG

introduction:
  <p>I am a <strong>technical team leader</strong> working at IBM Client Innovation Center, having previously spent
  over 5 years as a Java/JEE developer, in France and the United-Kingdom.</p>

primarylinks:
 - title: Blog
   url: http://remyg.fr
 - title: GitHub
   url: https://github.com/RemyG
 - title: LinkedIn
   url: https://www.linkedin.com/in/remygardette

skills:
  - Java
  - JEE
  - Oracle
  - Spring
  - Swing

education:
  - level: Master of Engineering (M.Eng.)
    date: 2009
    subject: Computer Science
    school: Institut National des Sciences Appliquées de Lyon

roles:
  - title: Technical Team Leader, Java/JEE
    start: October 2014
    end: Ongoing
    employer: IBM Client Innovation Center (Lille, FR)
    description: |
      <p>For a major aircraft manufacturer, I'm in charge of a team of 5 Java/JEE developers.
        <ul>
          <li>Coordinate the development activities</li>
          <li>Handle the communication between the team and the project manager</li>
          <li>Act as technical leader for junior developers</li>
          <li>Take part in the specifications, estimations, developments and maintenance of the applications.<br/>
            <span class="technos">Java/JEE, Spring, Hibernate, Swing, SOAP web-services, JBoss, Oracle</span><br/>
            <span class="technos">RTC (task and times control), Jazz (sources control), Alfresco (content management)</span>
          </li>
        </ul>
      </p>
  - title: Mid-Level Developer, Java/JEE
    start: February 2012
    end: October 2014
    employer: Multicom (Bristol, UK)
    description: |
      <p>Development and maintenance of the company's core product, FindAndBook, in its relation to the suppliers websites:
        <ul>
          <li>Online datamining (web-scraping of suppliers websites to retrieve all the required information and book flights).</li>
          <li>Maintenance of the Viewdata (Videotex) application to communicate with legacy suppliers.</li>
          <li>Writing of functional specifications for the integration of new modules.</li>
          <li>Organized the migration of all the source code management from SVN to Git.<br/>
          <span class="technos">Java/JEE, Spring, Oracle, Apache HttpClient, Axis2, Maven, Git</span><br/></li>
        </ul>
      </p>
  - title: Software Engineer, Java/JEE, PHP
    start: September 2009
    end: February 2012
    employer: Alten (Lyon, FR)
    description: |
      <p>Management and realization of different internal projects :
        <ul>
          <li>SMS, email and mail information campaigns sending platform<br/><span class="technos">Java, Oracle, GWT, Hibernate, JasperReports, Tomcat</span></li>
          <li>Company's website recruiting portal<br/><span class="technos">PHP, MySQL, PHP-MVC, Apache HTTPD</span></li>
          <li>Implementation of several webservices, called by different internal applications<br/><span class="technos">Java, Axis2, Oracle, Tomcat</span></li>
        </ul>
      </p>
      <p>Missions for clients :
        <ul>
          <li>Web porting of a VB application to PHP.<br/><span class="technos">PHP, PostGreSql, JavaScript, jQuery, jQGrid, Apache HTTPD</span></li>
          <li>Realization of an auditing application.<br/><span class="technos">PHP, PostGreSql, JavaScript, Apache HTTPD</span></li>
        </ul>
      </p>
  - title: Intern - Software Engineer, Java/JEE
    start: December 2008
    end: June 2009
    employer: Alten (Lyon, FR)
    description: |
      <p>
        <ul>
          <li>Internal SMS sending platform<br/><span class="technos">J2EE, GWT, Hibernate, Oracle, Tomcat</span></li>
          <li>Computer equipment lending application<br/><span class="technos">J2EE, GWT, Hibernate, Oracle, Tomcat</span></li>
        </ul>
      </p>

trainings:
  - name: Oracle Certified Associate, Java SE 7 Programmer
    date: May 2015
    description:
    link: https://www.youracclaim.com/badges/57bcb865-7a89-456f-b598-8716eaf75cf4
  - name: IBM Project Management courses
    date: 2015 - 2016
    description: Followed several Project Management courses provided by the IBM Project Management University.
    link:

languages:
  - name: French
    level: Native
  - name: English
    level: Full professional proficiency

stackoverflow:
  profileurl: http://stackoverflow.com/users/537994/remyg
  flairimageurl: http://stackoverflow.com/users/flair/537994.png

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  sass_dir: _sass
