# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Rémy Gardette
email: contact@remyg.fr
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://remyg.fr" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: remygardette
github_username:  RemyG

introduction:
  <p>I am a technical team leader working at IBM Client Innovation Center, having previously spent
  over 5 years as a Java/JEE developer, in France and the United-Kingdom.</p>

primarylinks:
 - title: Blog
   url: http://remyg.fr
 - title: GitHub
   url: https://github.com/RemyG
 - title: LinkedIn
   url: https://www.linkedin.com/in/remygardette

skills:
  - Java
  - JEE
  - Oracle
  - Spring
  - Swing

education:
  - level: Master of Engineering (M.Eng.)
    date: 2009
    subject: Computer Science
    school: Institut National des Sciences Appliquées de Lyon

roles:
  - title: Technical Team Leader, Java/JEE
    start: October 2014
    end: Ongoing
    employer: IBM Client Innovation Center (Lille, FR)
    description:
  - title: Mid-Level Developer, Java/JEE
    start: February 2012
    end: October 2014
    employer: Multicom (Bristol, UK)
    description:
  - title: Software Engineer, Jave/JEE
    start: September 2009
    end: February 2012
    employer: Alten (Lyon, FR)
    description:

languages:
  - name: French
    level: Native
  - name: English
    level: Full professional proficiency

stackoverflow:
  profileurl: http://stackoverflow.com/users/537994/remyg
  flairimageurl: http://stackoverflow.com/users/flair/537994.png

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  sass_dir: _sass
